name: Deploy to DreamHost via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Desplegar archivos vía FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; \
                   mirror -R -n -v . /github-test.rcdigital.cl/"
